%global sphinx_user sphinx
%global sphinx_group sphinx
Name: sphinx
Version: 2.2.10
Release: 1
Summary: Sphinx is an open source full text search server, designed from the ground up with performance, relevance (aka search quality), and integration simplicity in mind. 

Group:          Applications/Text
License:        GPLv2+
URL: http://sphinxsearch.com
Packager: Jess Portnoy <jess@packman.io>


Source0: %{name}-%{version}.tar.gz
BuildRoot:      %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

BuildRequires: expat-devel keyutils-libs-devel libcom_err-devel libselinux-devel libstdc++-devel pcre-devel zlib-devel 
Requires: expat, keyutils-libs, krb5-libs, libcom_err, libgcc, libselinux, libstdc++, mariadb-libs, openssl-libs, pcre, xz-libs, zlib
Requires(post): chkconfig
Requires(preun): chkconfig initscripts

%description
Sphinx is an open source full text search server, designed from the ground up with performance, relevance (aka search quality), and integration simplicity in mind. 

Sphinx lets you either batch index and search data stored in an SQL database, NoSQL storage, or just files quickly and easily — or index and search data on the fly, working with Sphinx pretty much as with a database server.

### dev package section
%package devel
Group: Development/Libraries
Summary: Development files for sphinx
#Requires: @@DEV_PACKAGE_REQUIRES@@ 

%description devel
Headers and additional dev files needed for building and developing on top of sphinx
### end dev package section

%prep
%setup -q

%build
%configure
make %{?_smp_mflags}
#inspect the Makefile and see if there is a test target, if so then:
#make test


%install
rm -rf %{buildroot}
make install DESTDIR=%{buildroot}
mkdir -p ${RPM_BUILD_ROOT}%_defaultdocdir/%{name} ${RPM_BUILD_ROOT}%_defaultlicensedir/%{name}
# place license and README files in the right place.
mkdir -p ${RPM_BUILD_ROOT}%_defaultlicensedir/%{name}
if [ -r LICENSE ];then
	cp LICENSE ${RPM_BUILD_ROOT}%_defaultlicensedir/%{name}/
fi
for F in AUTHORS ChangeLog COPYING NEWS INSTALL README*;do
        if [ -r $F ];then
                cp $F ${RPM_BUILD_ROOT}%_defaultdocdir/%{name}/
        fi
done




%clean
rm -rf %{buildroot}

%pre
getent group %{sphinx_group} >/dev/null || groupadd -r %{sphinx_group}
getent passwd %{sphinx_user} >/dev/null || \
useradd -r -g %{sphinx_group} -d %{sphinx_home} -s /bin/bash \
-c "Sphinx Search" %{sphinx_user}
exit 0

%post
/sbin/chkconfig --add searchd

%preun
if [ $1 = 0 ] ; then
    /sbin/service searchd stop >/dev/null 2>&1
    /sbin/chkconfig --del searchd
fi

%post -p /sbin/ldconfig -n libsphinxclient

%postun -p /sbin/ldconfig -n libsphinxclient


%files
%defattr(-,root,root,-)
%config(noreplace) /etc/sphinx.conf.dist
%config(noreplace) /etc/sphinx-min.conf.dist
/etc/example.sql
/usr/bin/indexer
/usr/bin/indextool
/usr/bin/searchd
/usr/bin/spelldump
/usr/bin/wordbreaker
/usr/share/man/man1/indexer.1.gz
/usr/share/man/man1/indextool.1.gz
/usr/share/man/man1/search.1.gz
/usr/share/man/man1/searchd.1.gz
/usr/share/man/man1/spelldump.1.gz
%doc
%_defaultlicensedir/%{name}
%doc %_defaultdocdir/%{name}/*

%files devel
%defattr(-,root,root)


%changelog
* Sat Apr 2 2016 Jess Portnoy <jess@packman.io> - 2.2.10-1
- Auto generated by Packman


